server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trip?characterEncoding=utf-8&servetTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
