server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/trip?characterEncoding=utf-8&servetTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 2000
      validationQuery: select 1
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      filters: stat, wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: valid

logging:
  config: log/locbak.xml
  level:
    root: info
    com.springboot.springbootdemo.controller: trace
    com.springboot.springbootdemo.service: debug
    com.springboot.springbootdemo.dao: debug
  file:
    name: classpath:log/trip.log